GET http://localhost:8080/tweets/?userId=c5d7f030-0144-4647-b771-3abe2c231eed HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhYjQyOTkwLWY3N2EtNDlhNS04YjZmLWQ4OTI4MDI5NTE0MyIsIm5hbWUiOiJ0ZXN0ZTEiLCJlbWFpbCI6InRlc3RlMUB0ZXN0ZS5jb20iLCJ1c2VybmFtZSI6InRlc3RlMSIsImlhdCI6MTcwNTEwNTg4OSwiZXhwIjoxNzA1MTA5NDg5fQ.5d8rwHaza3xHcOlePdNSctPLut6HHJxSUmdFZ0IYuQw