GET http://localhost:8080/tweets/?userId=1e1049be-ae7f-47c6-96d2-72aeefbe7381 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFlMTA0OWJlLWFlN2YtNDdjNi05NmQyLTcyYWVlZmJlNzM4MSIsIm5hbWUiOiJ0ZXN0ZTMiLCJlbWFpbCI6InRlc3RlM0B0ZXN0ZS5jb20iLCJ1c2VybmFtZSI6InRlc3RlMyIsImlhdCI6MTcwNTI4OTU3OSwiZXhwIjoxNzA1MzE4Mzc5fQ.fUeSFx1jBlT2YL0C9Doqc2AkDSMWejyf1WI5IkDGZsk