POST http://localhost:8080/likes/bb6b6052-85c9-41fd-8339-e0b674c1679c HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhYjQyOTkwLWY3N2EtNDlhNS04YjZmLWQ4OTI4MDI5NTE0MyIsIm5hbWUiOiJ0ZXN0ZTEiLCJlbWFpbCI6InRlc3RlMUB0ZXN0ZS5jb20iLCJ1c2VybmFtZSI6InRlc3RlMSIsImlhdCI6MTcwNTEwNTg4OSwiZXhwIjoxNzA1MTA5NDg5fQ.5d8rwHaza3xHcOlePdNSctPLut6HHJxSUmdFZ0IYuQw
